---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))

- name: resource-deploy-web-app
  type: cf
  source:
    api: API
    username: EMAIL
    password: PASSWORD
    organization: ORG
    space: SPACE
    skip_cert_check: false

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: repo
  - task: build
    file: repo/ci/tasks/build.yml
    params:
      PROJECT_TYPE: ((project-type))
- name: deploy
  serial: true
  plan:
  - put: resource-deploy-web-app
    params:
      manifest: out/manifest.yml
      environment_variables:
        key: value
        key2: value2
